# Site settings
title: Football Ground Guide for Girls
email: fggfg@thateden.co.uk
description: All the important info for planning your travels to football matches.
baseurl: "/fggfg"
url: ""
twitter_username: 
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Ground Girl" # Set default author name
      categories: "grounds"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
